---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: elasticlog
  name: beatload-cert
spec:
  commonName: beatload
  dnsNames:
  - beatload.local
  - beatload-svc
  duration: 2160h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-ca-issuer
  renewBefore: 360h
  secretName: beatload-cert
