---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: beatload
  name: beatload-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: beatload
  template:
    metadata:
      labels:
        component: beatload
    spec:
      containers:
      - image: gcr.io/google_containers/pause
        name: pause
      initContainers:
      - env:
        - name: CERT_VERIFY
          valueFrom:
            configMapKeyRef:
              key: elasticwait_cert_verify
              name: beatload-config
        - name: TIME_WAIT
          valueFrom:
            configMapKeyRef:
              key: elasticwait_time_wait
              name: beatload-config
        - name: MAX_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              key: elasticwait_max_attempts
              name: beatload-config
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: archmachina/elasticwait:0.1.3
        name: wait
      - args:
        - setup
        - --index-management
        - -e
        command:
        - /usr/share/filebeat/filebeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/filebeat:8.5.3-amd64
        name: filebeat-load
        volumeMounts:
        - mountPath: /usr/share/filebeat/certs
          name: beatload-cert
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: beatload-files
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      - args:
        - setup
        - --dashboards
        - -e
        command:
        - /usr/share/filebeat/filebeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/filebeat:8.5.3-amd64
        name: filebeat-load-dashboard
        volumeMounts:
        - mountPath: /usr/share/filebeat/certs
          name: beatload-cert
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: beatload-files
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      - args:
        - setup
        - --index-management
        - -e
        command:
        - /usr/share/metricbeat/metricbeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/metricbeat:8.5.3-amd64
        name: metricbeat-load
        volumeMounts:
        - mountPath: /usr/share/metricbeat/certs
          name: beatload-cert
        - mountPath: /usr/share/metricbeat/metricbeat.yml
          name: beatload-files
          subPath: metricbeat.yml
        - mountPath: /usr/share/metricbeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      - args:
        - setup
        - --dashboards
        - -e
        command:
        - /usr/share/metricbeat/metricbeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/metricbeat:8.5.3-amd64
        name: metricbeat-load-dashboard
        volumeMounts:
        - mountPath: /usr/share/metricbeat/certs
          name: beatload-cert
        - mountPath: /usr/share/metricbeat/metricbeat.yml
          name: beatload-files
          subPath: metricbeat.yml
        - mountPath: /usr/share/metricbeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      - args:
        - setup
        - --index-management
        - -e
        command:
        - /usr/share/auditbeat/auditbeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/auditbeat:8.5.3-amd64
        name: auditbeat-load
        volumeMounts:
        - mountPath: /usr/share/auditbeat/certs
          name: beatload-cert
        - mountPath: /usr/share/auditbeat/auditbeat.yml
          name: beatload-files
          subPath: auditbeat.yml
        - mountPath: /usr/share/auditbeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      - args:
        - setup
        - --dashboards
        - -e
        command:
        - /usr/share/auditbeat/auditbeat
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: beatload-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: beatload-config
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              key: kibana_host
              name: beatload-config
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              key: kibana_port
              name: beatload-config
        - name: INDEX_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: index_replicas
              name: beatload-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: beatload-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: beatload-credentials
        - name: KIBANA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kibana_username
              name: beatload-credentials
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kibana_password
              name: beatload-credentials
        image: docker.elastic.co/beats/auditbeat:8.5.3-amd64
        name: auditbeat-load-dashboard
        volumeMounts:
        - mountPath: /usr/share/auditbeat/certs
          name: beatload-cert
        - mountPath: /usr/share/auditbeat/auditbeat.yml
          name: beatload-files
          subPath: auditbeat.yml
        - mountPath: /usr/share/auditbeat/ilm-policy.json
          name: beatload-files
          subPath: ilm-policy.json
      volumes:
      - name: beatload-cert
        secret:
          secretName: beatload-cert
      - configMap:
          name: beatload-files
        name: beatload-files
