---
apiVersion: v1
data:
  elastic_password: "{{ elastic_password | b64encode }}"
  elastic_username: "{{ elastic_username | b64encode }}"
  kibana_password: "{{ kibana_password | b64encode }}"
  kibana_username: "{{ kibana_username | b64encode }}"
kind: Secret
metadata:
  labels:
    app: elasticlog
  name: beatload-credentials
type: Opaque
