---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kibana-ingress-ds
  labels:
    component: kibana-ingress
spec:
  selector:
    matchLabels:
      component: kibana-ingress
  template:
    metadata:
      labels:
        component: kibana-ingress
    spec:
      volumes:
        - name: kibana-files
          configMap:
            name: kibana-files
      containers:
        - name: ingress
          image: docker.io/library/haproxy:2.7.1
          env:
            - name: KIBANA_HOST
              value: "kibana-svc"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_DOMAIN
              value: "svc.cluster.local"
          volumeMounts:
            - name: kibana-files
              mountPath: "/usr/local/etc/haproxy/haproxy.cfg"
              subPath: ingress.cfg
          ports:
            - containerPort: 5601
              hostPort: 5601
