---

kind: Component

resources:
  - daemonset.yaml

replacements:
  - source:
      kind: ConfigMap
      name: kibana-config
      fieldPath: data.ingress_host_port
    targets:
      - select:
          group: apps
          version: v1
          kind: DaemonSet
          name: kibana-ingress-ds
        fieldPaths:
          - spec.template.spec.containers.[name=ingress].ports.[containerPort=5601].hostPort
