---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebeat-syslog-cert
spec:
  commonName: filebeat-syslog
  dnsNames:
  - filebeat-syslog.local
  - filebeat-syslog-svc
  duration: 2160h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-ca-issuer
  renewBefore: 360h
  secretName: filebeat-syslog-cert
