---
apiVersion: v1
data:
  filebeat.yml: "{{ include_file_str('files/filebeat-syslog.yml', template=True) }}"
  ilm-policy.json: "{{ include_file_str('files/ilm-policy.json') }}"
kind: ConfigMap
metadata:
  name: filebeat-syslog-files
---
apiVersion: v1
data:
  elastic_host: "{{ elastic_host }}"
  elastic_port: "{{ elastic_port }}"
  elasticwait_cert_verify: "{{ elasticwait_cert_verify }}"
  elasticwait_max_attempts: "{{ elasticwait_max_attempts }}"
  elasticwait_time_wait: "{{ elasticwait_time_wait }}"
  index_replicas: "{{ index_replicas }}"
kind: ConfigMap
metadata:
  name: filebeat-syslog-config
