---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticlog
    component: filebeat-syslog
  name: filebeat-syslog-ds
spec:
  selector:
    matchLabels:
      app: elasticlog
      component: filebeat-syslog
  template:
    metadata:
      labels:
        app: elasticlog
        component: filebeat-syslog
    spec:
      containers:
      - env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: filebeat-syslog-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: filebeat-syslog-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: filebeat-syslog-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: filebeat-syslog-credentials
        image: docker.elastic.co/beats/filebeat:8.5.3-amd64
        name: filebeat-syslog
        ports:
        - containerPort: 9000
          hostPort: 9000
          name: tcp-9000
          protocol: TCP
        - containerPort: 9001
          hostPort: 9001
          name: tcp-9001
          protocol: TCP
        - containerPort: 9002
          hostPort: 9002
          name: tcp-9002
          protocol: TCP
        - containerPort: 9003
          hostPort: 9003
          name: tcp-9003
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          name: udp-9000
          protocol: UDP
        - containerPort: 9001
          hostPort: 9001
          name: udp-9001
          protocol: UDP
        - containerPort: 9002
          hostPort: 9002
          name: udp-9002
          protocol: UDP
        - containerPort: 9003
          hostPort: 9003
          name: udp-9003
          protocol: UDP
        - containerPort: 9504
          hostPort: 9504
          name: udp-9504
          protocol: UDP
        - containerPort: 9506
          hostPort: 9506
          name: udp-9506
          protocol: UDP
        volumeMounts:
        - mountPath: /usr/share/filebeat/certs/
          name: filebeat-syslog-cert
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-syslog-files
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/ilm-policy.json
          name: filebeat-syslog-files
          subPath: ilm-policy.json
      initContainers:
      - env:
        - name: CERT_VERIFY
          valueFrom:
            configMapKeyRef:
              key: elasticwait_cert_verify
              name: filebeat-syslog-config
        - name: TIME_WAIT
          valueFrom:
            configMapKeyRef:
              key: elasticwait_time_wait
              name: filebeat-syslog-config
        - name: MAX_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              key: elasticwait_max_attempts
              name: filebeat-syslog-config
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: filebeat-syslog-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: filebeat-syslog-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: filebeat-syslog-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: filebeat-syslog-credentials
        image: archmachina/elasticwait:0.1.3
        name: wait
      volumes:
      - name: filebeat-syslog-cert
        secret:
          secretName: filebeat-syslog-cert
      - configMap:
          name: filebeat-syslog-files
        name: filebeat-syslog-files
