---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-dp
  labels:
    component: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        component: logstash
    spec:
      volumes:
        - name: logstash-pipeline-files
          configMap:
            name: logstash-pipeline-files
      initContainers:
        - name: wait
          image: archmachina/elasticwait:0.1.3
          env:
            - name: CERT_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elasticwait_cert_verify
            - name: TIME_WAIT
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elasticwait_time_wait
            - name: MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elasticwait_max_attempts
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elastic_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_password
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.5.3-amd64
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: java_opts
            - name: ELASTIC_URI
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: elastic_uri
            - name: XPACK_MONITORING_ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: xpack_monitoring_uri
            - name: XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITY
              value: /usr/share/logstash/certs/ca.crt
            - name: XPACK_MONITORING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_username
            - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_password
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-credentials
                  key: elastic_password
          volumeMounts:
            - name: logstash-pipeline-files
              mountPath: /usr/share/logstash/pipeline
          ports:
            - containerPort: 5044
