---

kind: Component

resources:
  - service.yaml
  - deployment.yaml

replacements:
  - source:
      kind: ConfigMap
      name: logstash-config
      fieldPath: data.replicas
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: logstash-dp
        fieldPaths:
          - spec.replicas
