---
apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  labels:
    component: logstash
spec:
  selector:
    component: logstash
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
