---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-ingress-ds
  labels:
    component: elastic-ingress
spec:
  selector:
    matchLabels:
      component: elastic-ingress
  template:
    metadata:
      labels:
        component: elastic-ingress
    spec:
      volumes:
        - name: elastic-files
          configMap:
            name: elastic-files
      containers:
        - name: ingress
          image: docker.io/library/haproxy:2.7.1
          env:
            - name: ELASTIC_HOST
              value: "elastic-svc"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_DOMAIN
              value: "svc.cluster.local"
          volumeMounts:
            - name: elastic-files
              mountPath: "/usr/local/etc/haproxy/haproxy.cfg"
              subPath: ingress.cfg
          ports:
            - containerPort: 9200
              hostPort: 9200
