---

kind: Component

resources:
  - daemonset.yaml

replacements:
  - source:
      kind: ConfigMap
      name: filebeat-netflow-config
      fieldPath: data.netflow_host_port
    targets:
      - select:
          group: apps
          version: v1
          kind: DaemonSet
          name: filebeat-netflow-ds
        fieldPaths:
          - spec.template.spec.containers.[name=filebeat-netflow].ports.[name=udp-2055].hostPort
