---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-dp
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      volumes:
        - name: kibana-cert
          secret:
            secretName: kibana-cert
      initContainers:
        - name: wait
          image: archmachina/elasticwait:0.1.3
          env:
            - name: CERT_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticwait_cert_verify
            - name: TIME_WAIT
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticwait_time_wait
            - name: MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticwait_max_attempts
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticwait_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticwait_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: elastic_password
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.5.3-amd64
          env:
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elastic_hosts
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "[\"/usr/share/kibana/config/certs/ca.crt\"]"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: certificate
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: elastic_username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: elastic_password
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_PUBLICBASEURL
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: publicbaseurl
            - name: SERVER_SSL_CERTIFICATE
              value: /usr/share/kibana/config/certs/tls.crt
            - name: SERVER_SSL_KEY
              value: /usr/share/kibana/config/certs/tls.key
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: kibana_key
          volumeMounts:
            - name: kibana-cert
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
          ports:
            - containerPort: 5601
