---

kind: Component

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

replacements:
  - source:
      kind: ConfigMap
      name: kibana-config
      fieldPath: data.replicas
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: kibana-dp
        fieldPaths:
          - spec.replicas
  - source:
      kind: ConfigMap
      name: kibana-config
      fieldPath: data.fqdn
    targets:
      - select:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: kibana-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
