---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatload-dp
  labels:
    component: beatload
spec:
  replicas: 1
  selector:
    matchLabels:
      component: beatload
  template:
    metadata:
      labels:
        component: beatload
    spec:
      volumes:
        - name: beatload-files
          configMap:
            name: beatload-files
      initContainers:
        - name: wait
          image: archmachina/elasticwait:0.1.3
          env:
            - name: CERT_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elasticwait_cert_verify
            - name: TIME_WAIT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elasticwait_time_wait
            - name: MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elasticwait_max_attempts
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
        - name: filebeat-load
          image: docker.elastic.co/beats/filebeat:8.5.3-amd64
          command: ['/usr/share/filebeat/filebeat']
          args:
            - "setup"
            - "--index-management"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: beatload-files
              mountPath: /usr/share/filebeat/ilm-policy.json
              subPath: ilm-policy.json
        - name: filebeat-load-dashboard
          image: docker.elastic.co/beats/filebeat:8.5.3-amd64
          command: ['/usr/share/filebeat/filebeat']
          args:
            - "setup"
            - "--dashboards"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: beatload-files
              mountPath: /usr/share/filebeat/ilm-policy.json
              subPath: ilm-policy.json
        - name: metricbeat-load
          image: docker.elastic.co/beats/metricbeat:8.5.3-amd64
          command: ['/usr/share/metricbeat/metricbeat']
          args:
            - "setup"
            - "--index-management"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/metricbeat/metricbeat.yml
              subPath: metricbeat.yml
            - name: beatload-files
              mountPath: /usr/share/metricbeat/ilm-policy.json
              subPath: ilm-policy.json
        - name: metricbeat-load-dashboard
          image: docker.elastic.co/beats/metricbeat:8.5.3-amd64
          command: ['/usr/share/metricbeat/metricbeat']
          args:
            - "setup"
            - "--dashboards"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/metricbeat/metricbeat.yml
              subPath: metricbeat.yml
            - name: beatload-files
              mountPath: /usr/share/metricbeat/ilm-policy.json
              subPath: ilm-policy.json
        - name: auditbeat-load
          image: docker.elastic.co/beats/auditbeat:8.5.3-amd64
          command: ['/usr/share/auditbeat/auditbeat']
          args:
            - "setup"
            - "--index-management"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/auditbeat/auditbeat.yml
              subPath: auditbeat.yml
            - name: beatload-files
              mountPath: /usr/share/auditbeat/ilm-policy.json
              subPath: ilm-policy.json
        - name: auditbeat-load-dashboard
          image: docker.elastic.co/beats/auditbeat:8.5.3-amd64
          command: ['/usr/share/auditbeat/auditbeat']
          args:
            - "setup"
            - "--dashboards"
            - "-e"
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: elastic_port
            - name: KIBANA_HOST
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_host
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: kibana_port
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: beatload-config
                  key: index_replicas
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: elastic_password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatload-credentials
                  key: kibana_password
          volumeMounts:
            - name: beatload-files
              mountPath: /usr/share/auditbeat/auditbeat.yml
              subPath: auditbeat.yml
            - name: beatload-files
              mountPath: /usr/share/auditbeat/ilm-policy.json
              subPath: ilm-policy.json
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
