---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elasticlog-ca-issuer
spec:
  ca:
    secretName: elasticlog-selfsigned-issuer-certificate
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elasticlog-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticlog-selfsigned-issuer-certificate
spec:
  commonName: elasticlog-selfsigned-issuer-certificate
  duration: 8760h
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 1000h
  secretName: elasticlog-selfsigned-issuer-certificate
