---

kind: Component

resources:
  - service.yaml
  - statefulset.yaml
  - ingress.yaml
  - deployment.yaml

replacements:
  - source:
      kind: ConfigMap
      name: elastic-config
      fieldPath: data.replicas
    targets:
      - select:
          group: apps
          version: v1
          kind: StatefulSet
          name: elastic-ss
        fieldPaths:
          - spec.replicas
  - source:
      kind: ConfigMap
      name: elastic-config
      fieldPath: data.fqdn
    targets:
      - select:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: elastic-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: elastic-config
      fieldPath: data.storage_class
    targets:
      - select:
          group: apps
          version: v1
          kind: StatefulSet
          name: elastic-ss
        fieldPaths:
          - spec.volumeClaimTemplates.0.spec.storageClassName
