---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: elasticlog
  name: filebeat-netflow-cert
spec:
  commonName: filebeat-netflow
  dnsNames:
  - filebeat-netflow.local
  - filebeat-netflow-svc
  duration: 2160h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-ca-issuer
  renewBefore: 360h
  secretName: filebeat-netflow-cert
