---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticlog
    component: filebeat-netflow
  name: filebeat-netflow-ds
spec:
  selector:
    matchLabels:
      app: elasticlog
      component: filebeat-netflow
  template:
    metadata:
      labels:
        app: elasticlog
        component: filebeat-netflow
    spec:
      containers:
      - env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: filebeat-netflow-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: filebeat-netflow-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: filebeat-netflow-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: filebeat-netflow-credentials
        image: docker.elastic.co/beats/filebeat:8.5.3-amd64
        name: filebeat-netflow
        ports:
        - containerPort: 2055
          hostPort: 2055
          name: udp-2055
          protocol: UDP
        volumeMounts:
        - mountPath: /usr/share/filebeat/certs/
          name: filebeat-netflow-cert
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-netflow-files
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/ilm-policy.json
          name: filebeat-netflow-files
          subPath: ilm-policy.json
      initContainers:
      - env:
        - name: CERT_VERIFY
          valueFrom:
            configMapKeyRef:
              key: elasticwait_cert_verify
              name: filebeat-netflow-config
        - name: TIME_WAIT
          valueFrom:
            configMapKeyRef:
              key: elasticwait_time_wait
              name: filebeat-netflow-config
        - name: MAX_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              key: elasticwait_max_attempts
              name: filebeat-netflow-config
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elastic_host
              name: filebeat-netflow-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elastic_port
              name: filebeat-netflow-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: filebeat-netflow-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: filebeat-netflow-credentials
        image: archmachina/elasticwait:0.1.3
        name: wait
      volumes:
      - name: filebeat-netflow-cert
        secret:
          secretName: filebeat-netflow-cert
      - configMap:
          name: filebeat-netflow-files
        name: filebeat-netflow-files
