---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticlog
    component: elastic-ingress
  name: elastic-ingress-ds
spec:
  selector:
    matchLabels:
      app: elasticlog
      component: elastic-ingress
  template:
    metadata:
      labels:
        app: elasticlog
        component: elastic-ingress
    spec:
      containers:
      - env:
        - name: ELASTIC_HOST
          value: elastic-svc
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_DOMAIN
          value: svc.cluster.local
        image: docker.io/library/haproxy:2.7.1
        name: ingress
        ports:
        - containerPort: 9200
          hostPort: "{{ ingress_host_port }}"
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: elastic-files
          subPath: ingress.cfg
      volumes:
      - configMap:
          name: elastic-files
        name: elastic-files
