---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: elasticlog
  name: elastic-ingress
spec:
  rules:
  - host: "{{ fqdn }}"
    http:
      paths:
      - backend:
          service:
            name: elastic-svc
            port:
              number: 9200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ fqdn }}
    secretName: elastic-cert
