---
apiVersion: v1
data:
  elastic_password: "{{ elastic_password | b64encode }}"

  filebeat_password: "{{ filebeat_password | b64encode }}"
  filebeat_username: "{{ filebeat_username | b64encode }}"

  beats_system_password: "{{ beats_system_password | b64encode }}"
  kibana_system_password: "{{ kibana_system_password | b64encode }}"
  logstash_system_password: "{{ logstash_system_password | b64encode }}"

  localadmin_password: "{{ localadmin_password | b64encode }}"
  localadmin_username: "{{ localadmin_username | b64encode }}"

  logstash_password: "{{ logstash_password | b64encode }}"
  logstash_username: "{{ logstash_username | b64encode }}"
kind: Secret
metadata:
  name: elastic-credentials
type: Opaque
