---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: elastic
  name: elastic-svc
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elastic
  type: ClusterIP
