---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash-ingress-ds
  labels:
    component: logstash-ingress
spec:
  selector:
    matchLabels:
      component: logstash-ingress
  template:
    metadata:
      labels:
        component: logstash-ingress
    spec:
      volumes:
        - name: logstash-files
          configMap:
            name: logstash-files
      containers:
        - name: ingress
          image: docker.io/library/haproxy:2.7.1
          env:
            - name: LOGSTASH_HOST
              value: "logstash-svc"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_DOMAIN
              value: "svc.cluster.local"
          volumeMounts:
            - name: logstash-files
              mountPath: "/usr/local/etc/haproxy/haproxy.cfg"
              subPath: ingress.cfg
          ports:
            - containerPort: 5044
              hostPort: 5044
