---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: elasticlog
  name: kibana-cert
spec:
  commonName: kibana
  dnsNames:
  - kibana.local
  - kibana-svc
  - {{ fqdn }}
  duration: 2160h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-ca-issuer
  renewBefore: 360h
  secretName: kibana-cert
