---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: kibana-ingress
  name: kibana-ingress-ds
spec:
  selector:
    matchLabels:
      component: kibana-ingress
  template:
    metadata:
      labels:
        component: kibana-ingress
    spec:
      containers:
      - env:
        - name: KIBANA_HOST
          value: kibana-svc
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_DOMAIN
          value: svc.cluster.local
        image: docker.io/library/haproxy:2.7.1
        name: ingress
        ports:
        - containerPort: 5601
          hostPort: {{ ingress_host_port }}
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: kibana-files
          subPath: ingress.cfg
      volumes:
      - configMap:
          name: kibana-files
        name: kibana-files
