---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: kibana
  name: kibana-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              key: elastic_hosts
              name: kibana-config
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: '["/usr/share/kibana/config/certs/ca.crt"]'
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: certificate
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: kibana-credentials
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: kibana-credentials
        - name: SERVER_SSL_ENABLED
          value: "true"
        - name: SERVER_PUBLICBASEURL
          valueFrom:
            configMapKeyRef:
              key: publicbaseurl
              name: kibana-config
        - name: SERVER_SSL_CERTIFICATE
          value: /usr/share/kibana/config/certs/tls.crt
        - name: SERVER_SSL_KEY
          value: /usr/share/kibana/config/certs/tls.key
        image: docker.elastic.co/kibana/kibana:8.5.3-amd64
        name: kibana
        ports:
        - containerPort: 5601
        volumeMounts:
        - mountPath: /usr/share/kibana/config/certs
          name: kibana-cert
          readOnly: true
      initContainers:
      - env:
        - name: CERT_VERIFY
          valueFrom:
            configMapKeyRef:
              key: elasticwait_cert_verify
              name: kibana-config
        - name: TIME_WAIT
          valueFrom:
            configMapKeyRef:
              key: elasticwait_time_wait
              name: kibana-config
        - name: MAX_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              key: elasticwait_max_attempts
              name: kibana-config
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              key: elasticwait_host
              name: kibana-config
        - name: ELASTIC_PORT
          valueFrom:
            configMapKeyRef:
              key: elasticwait_port
              name: kibana-config
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: elastic_username
              name: kibana-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic_password
              name: kibana-credentials
        image: archmachina/elasticwait:0.1.3
        name: wait
      volumes:
      - name: kibana-cert
        secret:
          secretName: kibana-cert
