---
apiVersion: v1
data:
  elastic_password: "{{ elastic_password | b64encode }}"
  elastic_username: "{{ elastic_username | b64encode }}"
{% if saved_objects_key is defined %}
  saved_objects_key: "{{ saved_objects_key | b64encode }}"
{% endif %}
{% if reporting_key is defined %}
  reporting_key: "{{ reporting_key | b64encode }}"
{% endif %}
{% if security_key is defined %}
  security_key: "{{ security_key | b64encode}}"
{% endif %}
kind: Secret
metadata:
  name: kibana-credentials
type: Opaque
