---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticlog
    component: kibana
  name: kibana-svc
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: elasticlog
    component: kibana
  type: ClusterIP
