---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logstash-cert
spec:
  commonName: logstash
  dnsNames:
  - logstash.local
  - logstash-svc
  duration: 2160h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: elasticlog-ca-issuer
  renewBefore: 360h
  secretName: logstash-cert
