---
apiVersion: v1
data:
  elastic_password: "{{ elastic_password | b64encode }}"
  elastic_username: "{{ elastic_username | b64encode }}"
kind: Secret
metadata:
  name: logstash-credentials
type: Opaque
