---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticlog
    component: logstash
  name: logstash-svc
spec:
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: elasticlog
    component: logstash
  type: ClusterIP
