---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-syslog-ds
  labels:
    component: filebeat-syslog
spec:
  selector:
    matchLabels:
      component: filebeat-syslog
  template:
    metadata:
      labels:
        component: filebeat-syslog
    spec:
      volumes:
        - name: filebeat-syslog-files
          configMap:
            name: filebeat-syslog-files
      initContainers:
        - name: wait
          image: archmachina/elasticwait:0.1.3
          env:
            - name: CERT_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elasticwait_cert_verify
            - name: TIME_WAIT
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elasticwait_time_wait
            - name: MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elasticwait_max_attempts
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elastic_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: filebeat-syslog-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filebeat-syslog-credentials
                  key: elastic_password
      containers:
        - name: filebeat-syslog
          image: docker.elastic.co/beats/filebeat:8.5.3-amd64
          volumeMounts:
            - name: filebeat-syslog-files
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: filebeat-syslog-files
              mountPath: /usr/share/filebeat/ilm-policy.json
              subPath: ilm-policy.json
          env:
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: elastic_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: filebeat-syslog-credentials
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filebeat-syslog-credentials
                  key: elastic_password
            - name: INDEX_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: filebeat-syslog-config
                  key: index_replicas
          ports:
            - name: "tcp-9000"
              protocol: TCP
              containerPort: 9000
              hostPort: 9000
            - name: "tcp-9001"
              protocol: TCP
              containerPort: 9001
              hostPort: 9001
            - name: "tcp-9002"
              protocol: TCP
              containerPort: 9002
              hostPort: 9002
            - name: "tcp-9003"
              protocol: TCP
              containerPort: 9003
              hostPort: 9003
            - name: "udp-9000"
              protocol: UDP
              containerPort: 9000
              hostPort: 9000
            - name: "udp-9001"
              protocol: UDP
              containerPort: 9001
              hostPort: 9001
            - name: "udp-9002"
              protocol: UDP
              containerPort: 9002
              hostPort: 9002
            - name: "udp-9003"
              protocol: UDP
              containerPort: 9003
              hostPort: 9003
            - name: "udp-9504"
              protocol: UDP
              containerPort: 9504
              hostPort: 9504
            - name: "udp-9506"
              protocol: UDP
              containerPort: 9506
              hostPort: 9506
